format_version: 3
pipelines:
  dsa-quickstart-ci:
    group: Application
    materials:
      repo:
        git: https://github.com/DaSandoval/practica.git
        branch: master
        whitelist:
            - webApplication/**/*
    stages:
      - Build:
          jobs:
            Building:
              tasks:
                - exec:
                    working_directory: webApplication
                    command: ./gradlew
                    arguments:
                      - clean
                      - assemble
              artifacts:
                - build:
                    source: webApplication/build/libs/*.jar
                    destination: jar
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    working_directory: webApplication
                    command: ./gradlew
                    arguments:
                      - test
              artifacts:
                - build:
                    source: webApplication/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: webApplication/build/test-results/test/*.xml
                    destination: xml
              tabs:
                unit_test: html/index.html
      - Code_Quality:
          jobs:
            Sonarqube:
              tasks:
                - exec:
                    working_directory: webApplication
                    command: ./gradlew
                    arguments:
                      - sonarqube
      - owaps_vulnerability:
          jobs:
            dependency_CheckAnalyze:
              tasks:
                - exec:
                    working_directory: webApplication
                    command: ./gradlew
                    arguments: 
                      - dependencyCheckAnalyze
              artifacts:
                - build:
                    source: webApplication/build/reports/**/*
                    destination: html
